repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.3.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==18.9b0]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
        language_version: python3
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories=.:src']
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
    -   id: pyupgrade
        args: [--keep-percent-format]
